name: Linux arm64

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    strategy:
      matrix:
        options: [--with-sb-thread]
        # subfeatures: ['']
        # include:
        #   - { subfeatures: fasteval, options: --with-sb-fasteval --without-sb-eval }

      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: install host sbcl
      run: |
        sudo apt-get -qq update | true
        sudo apt-get -qq install sbcl libcapstone-dev libzstd-dev

    - name: build
      env:
        SBCL_MAKE_TARGET_2_OPTIONS: --disable-ldb --disable-debugger
      run: ./make.sh ${{ matrix.options }} --with-sb-core-compression --xc-host='sbcl --dynamic-space-size 700MB --lose-on-corruption --disable-ldb --disable-debugger'
    - name: test-fasteval
      if: matrix.subfeatures == 'fasteval'
      run: cd tests; ./run-tests.sh --evaluator-mode interpret
    - name: test
      run: cd tests; ./run-tests.sh --slow
    - name: ansi-test
      run: cd tests; ./ansi-tests.sh
