name: Linux arm

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v1
    - name: install host sbcl
      run: |
        sudo dpkg --add-architecture armhf
        sudo apt-get -qq update | true
        sudo apt-get -qq install 
        sudo apt-get -qq install libc6:armhf gcc-arm-linux-gnueabihf sbcl

    - name: build
      env:
        SBCL_MAKE_TARGET_2_OPTIONS: --disable-ldb --disable-debugger
        CC: arm-linux-gnueabihf-gcc
      run: ./make.sh --xc-host='sbcl --dynamic-space-size 700MB --lose-on-corruption --disable-ldb --disable-debugger' --arch=arm

    - name: test
      env:
        CC: arm-linux-gnueabihf-gcc
      run: cd tests; ./run-tests.sh
    - name: ansi-test
      run: cd tests; ./ansi-tests.sh
